//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador_de_Consultas_Médicas.Repositorio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class clinicas_has_medicos
    {

        [Display(Name = "Horário de trabalho")]
        public string horarioTrabalho { get; set; }

        [Display(Name = "Dias da semana")]
        public string diasSemana { get; set; }
        public int medicos_idMedico { get; set; }
        public int clinicas_idClinica { get; set; }
    
        public virtual medicos medicos { get; set; }
        public virtual clinicas clinicas { get; set; }
    }
}
