//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador_de_Consultas_Médicas.Repositorio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class clinicas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clinicas()
        {
            this.consultas = new HashSet<consultas>();
            this.clinicas_has_medicos = new HashSet<clinicas_has_medicos>();
        }
        [Key]
        public int idClinica { get; set; }

        [Required(ErrorMessage = "Digite o nome da clínica")]
        public string nome { get; set; }

        [Display(Name = "CNPJ")]
        [Required(ErrorMessage = "Informe o cnpj")]
        public int cnpj { get; set; }

        [Display(Name = "Especialidades")]
        public string ds_especialidades { get; set; }
        public string endereco { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public int cep { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }

        [Required(ErrorMessage = "Informe um e-mail")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Informe um email válido")]
        public string email { get; set; }
        public int telefone { get; set; }
        public Nullable<int> fax { get; set; }

        [Display(Name = "Horário de funcionamento")]
        public string hrFuncionamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consultas> consultas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clinicas_has_medicos> clinicas_has_medicos { get; set; }
    }
}
