//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador_de_Consultas_Médicas.Repositorio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class consultas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public consultas()
        {
            this.pagamentos = new HashSet<pagamentos>();
        }
    
        public int idConsulta { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Data da consulta")]
        [Required(ErrorMessage = "Informe uma data para a consulta")]
        public System.DateTime dataConsulta { get; set; }
        public System.TimeSpan horario { get; set; }
        public Nullable<int> check_in { get; set; }
        public Nullable<int> check_out { get; set; }
        public int pacientes_idPaciente { get; set; }
        public int medicos_idMedico { get; set; }
        public int clinicas_idClinica { get; set; }
    
        public virtual pacientes pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagamentos> pagamentos { get; set; }
        public virtual medicos medicos { get; set; }
        public virtual clinicas clinicas { get; set; }
    }
}
