//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador_de_Consultas_Médicas.Repositorio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class pacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pacientes()
        {
            this.consultas = new HashSet<consultas>();
        }
        
        [Key]
        public int idPaciente { get; set; }

        [Required(ErrorMessage = "Informe o nome do paciente")]
        public string nome { get; set; }

        [Range(3, 100)]
        public short idade { get; set; }

        [Display(Name = "Data de nascimento")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime dataNasc { get; set; }
        public int cpf { get; set; }
        public int rg { get; set; }

        [Display(Name = "Endereço")]
        public string endereco { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string estadoCivil { get; set; }

        [Required(ErrorMessage = "Informe o telefone")]
        public int telefone { get; set; }
        public Nullable<int> celular { get; set; }

        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Informe um email válido")]
        public string email { get; set; }

        [DataType(DataType.Password)]
        public string senhaAcesso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consultas> consultas { get; set; }
    }
}
