//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador_de_Consultas_Médicas.Repositorio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class pagamentos
    {

        [Key]
        public int idPagamento { get; set; }

        [Display(Name = "Tipo de pagamento")]
        public string tipoPag { get; set; }

        [Required]
        public double valorTotal { get; set; }

        [Display(Name = "Data de pagamento")]
        public System.DateTime dataPgto { get; set; }
        public string tipoParcVista { get; set; }

        [Required]
        [Display(Name = "Quantidade de parcelas")]
        public Nullable<short> qtdeParcelas { get; set; }
        public Nullable<int> conta { get; set; }
        public Nullable<int> agencia { get; set; }
        public Nullable<int> cartaoCred { get; set; }
        public Nullable<double> descontos { get; set; }
        public int consultas_idConsulta { get; set; }
        public int convenios_idConvenio { get; set; }
    
        public virtual consultas consultas { get; set; }
        public virtual convenios convenios { get; set; }
    }
}
