//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador_de_Consultas_Médicas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class consultas
    {
        [Key]
        public int idConsulta { get; set; }

        [Display(Name = "Data da consulta")]
        public string data { get; set; }

        [Display(Name = "Horário")]
        public string horario { get; set; }

        [Display(Name = "Check-in")]
        public Nullable<int> check_in { get; set; }

        [Display(Name = "Check-out")]
        public Nullable<int> check_out { get; set; }
        public int pacientes_idPaciente { get; set; }
        public int medicos_idMedico { get; set; }
        public int clinicas_idClinica { get; set; }

        public virtual pacientes pacientes { get; set; }
        public virtual medicos medicos { get; set; }
        public virtual clinicas clinicas { get; set; }
    }
}
