//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador_de_Consultas_Médicas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class medicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medicos()
        {
            this.consultas = new HashSet<consultas>();
            this.avaliacoes = new HashSet<avaliacoes>();
            this.agenda = new HashSet<agenda>();
        }

        [Key]
        public int idMedico { get; set; }

        [Required(ErrorMessage = "Informe seu nome")]
        [Display(Name = "Nome")]
        public string nome { get; set; }

        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail em formato inválido.")]
        [Required(ErrorMessage = "Informe seu e-mail")]
        [Display(Name = "E-mail")]
        public string email { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Digite uma senha")]
        [Display(Name = "Senha")]
        public string senha { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Confirme a senha")]
        [Display(Name = "Confirmar senha")]
        [Compare("senha", ErrorMessage = "As senhas não conferem")]
        public string confirmarSenha { get; set; }

        [DataType(DataType.Currency)]
        [Display(Name = "Preço")]
        public string preco { get; set; }

        [Display(Name = "Situação")]
        public short situacao { get; set; }

        [Display(Name = "Especialidade")]
        public int especialidades_idEspecialidade { get; set; }

        [Display(Name = "Clínica")]
        public int clinicas_idClinica { get; set; }
        public short adm { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consultas> consultas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<avaliacoes> avaliacoes { get; set; }
        public virtual especialidades especialidades { get; set; }
        public virtual clinicas clinicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda> agenda { get; set; }
    }
}
