//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador_de_Consultas_Médicas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class pacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pacientes()
        {
            this.consultas = new HashSet<consultas>();
            this.avaliacoes = new HashSet<avaliacoes>();
        }
    
        [key]
        public int idPaciente { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Informe seu nome")]
        public string nome { get; set; }

        [Required(ErrorMessage = "Informe seu CPF")]
        [Display(Name = "CPF")]
        public string cpf { get; set; }

        [Required(ErrorMessage = "Informe seu endereço")]
        [Display(Name = "Endereço")]
        public string endereco { get; set; }

        [Required(ErrorMessage = "Informe seu bairro")]
        [Display(Name = "Bairro")]
        public string bairro { get; set; }

        [Required(ErrorMessage = "Informe sua cidade")]
        [Display(Name = "Cidade")]
        public string cidade { get; set; }

        [Required(ErrorMessage = "Informe seu estado")]
        [Display(Name = "Estado")]
        public string estado { get; set; }

        [Required(ErrorMessage = "Informe seu telefone")]
        [Display(Name = "Telefone")]
        public string telefone { get; set; }

        [Display(Name = "Celular")]
        public string celular { get; set; }

        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail inválido")]
        [Required(ErrorMessage = "Informe seu e-mail")]
        [Display(Name = "E-mail")]
        public string email { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Informe sua senha")]
        [Display(Name = "Senha")]
        public string senha { get; set; }

        [DataType(DataType.Password)]
        [Compare("senha", ErrorMessage = "As senhas não conferem")]
        [Required(ErrorMessage = "Digite a confirmação da senha")]
        [Display(Name = "Senha")]
        public string confirmarSenha{ get; set; }

        [Display(Name = "Convênio")]
        public int convenios_idConvenio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consultas> consultas { get; set; }
        public virtual convenios convenios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<avaliacoes> avaliacoes { get; set; }
    }
}
